/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

import java.util.Random;
/**
 *
 * @author almei
 */
public class telaGenio extends javax.swing.JFrame {

    /**
     * Creates new form telaGenio
     */
    public telaGenio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnValor = new javax.swing.JSpinner();
        bntPalpite = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        lblGenio = new javax.swing.JLabel();
        lblBalaoDeFala = new javax.swing.JLabel();
        lblFala = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(spnValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        bntPalpite.setText("Palpite");
        bntPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(bntPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 130, 60));

        lblValor.setText("Valor");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 22));

        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/ImgGenio.png"))); // NOI18N
        getContentPane().add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        lblBalaoDeFala.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblBalaoDeFala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/ImgBalaoDeFala.png"))); // NOI18N
        getContentPane().add(lblBalaoDeFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        lblFala.setText("<html>Vou pensar em um valor<br>de 1 a 5.<br>Tente adivinhar.</html>");
        getContentPane().add(lblFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPalpiteActionPerformed
       
        //definindo um numero aleatorio cada vez que o botão é clicado 
        Random random = new Random();
        int numeroAleatorio = random.nextInt(5) + 1; 
        
        //recebendo o valor escolhido
        int valor = (int)spnValor.getValue();
        
        
        
        //testa se o valor é igual ou não
        if(valor == numeroAleatorio){
            
            lblFala.setText("Acertou!");
            
        }
        else{
            
            lblFala.setText("Errou. Eu pensei em " + numeroAleatorio);
     
        }
        
    }//GEN-LAST:event_bntPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPalpite;
    private javax.swing.JLabel lblBalaoDeFala;
    private javax.swing.JLabel lblFala;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblValor;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
